# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.11


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

- repo: https://github.com/pycqa/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: ['-iii', '-ll']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
    - id: pycln
      args: ["--config=pyproject.toml"]
