# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.11


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace


- repo: local
  hooks:
    - id: bandit
      name: bandit
      entry: bandit
      language: system
      types: [python]
      args: ['-iii', '-ll']

- repo: local
  hooks:
    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]

- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]

- repo: local
  hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]

- repo: local
  hooks:
    - id: pycln
      name: pycln
      entry: pycln
      language: system
      types: [python]
      args: ["--config=pyproject.toml"]
