# Generated by Django 4.2.4 on 2023-08-10 19:38

from django.db import migrations, models

import helpers.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotifyAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, helpers.mixins.ModelDifferenceMixin),
        ),
    ]
