# Generated by Django 4.2.4 on 2023-08-12 12:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import helpers.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "session_closed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, helpers.mixins.ModelDifferenceMixin),
        ),
        migrations.CreateModel(
            name="ChatSessionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, helpers.mixins.ModelDifferenceMixin),
        ),
        migrations.CreateModel(
            name="ChatSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("sequence", models.BigIntegerField(editable=False)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User from which message was originated",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, helpers.mixins.ModelDifferenceMixin),
        ),
        migrations.AddConstraint(
            model_name="chatsessionuser",
            constraint=models.UniqueConstraint(
                fields=("chat_session", "user"),
                name="chat_session_user_unique_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsessionmessage",
            constraint=models.UniqueConstraint(
                fields=("chat_session", "sequence"),
                name="chat_session_sequence_unique_key",
            ),
        ),
    ]
